apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: ml
  annotations:
    serving.kserve.io/s3-endpoint: s3.amazonaws.com
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-region: us-west-1
type: Opaque
Data:
  AWS_ACCESS_KEY_ID: QUtJQVdBQTY2VDJSUUFSWEkzSFQK

  AWS_SECRET_ACCESS_KEY: Y2RrRXZjWERQeWR2SEV0VC82ZUZIVlNjeWJ1eFEwMFJyQnhaNWl4Tgo=
 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-s3-access
  namespace: ml
secrets:
- name: s3-secret
